### ISSUE TITLE
Wrong encoding of ppid delivered in the SndRcvInfo when sending SCTP data

### ISSUE THREAD

**Issue by sysarch-repo** [thebagchi/sctp-go#2]
When sending SCTP message with NGAP payload by using:
`info := &sctp.SCTPSndRcvInfo{Ppid: 60} `
and
`conn.SendMsg(msgBytes, info)`
then wireshark is showing in the SCTP DATA chunk section:
`Payload protocol identifier: Unknown (1006632960)`
that is 0x3c000000 instead of the intended 0x0000003c

The workaround is using 0x3c000000 as follows:
`info := &sctp.SCTPSndRcvInfo{Ppid: 1006632960}`
with wireshark correctly showing:
`Payload protocol identifier: NGAP (60)`

**Comment by thebagchi** [comment]
Hi @richardjudgeman 
I have refered to the following RFC.
https://datatracker.ietf.org/doc/html/rfc6458

> sinfo_ppid:  This value in sendmsg() is an unsigned integer that is
>                     passed to the remote end in each user message.  In recvmsg(), this
>                    value is the same information that was passed by the upper layer
>                    in the peer application.  Please note that the SCTP stack performs
>                   no byte order modification of this field.  For example, if the
>                   DATA chunk has to contain a given value in network byte order, the
>                   SCTP user has to perform the htonl() computation.

Kindly close the issue, if it helps.

**Comment by sysarch-repo** [comment]
Hi @thebagchi
I have added the conversion function to my code as per your suggestion. I am closing the issue. Thanks a lot for your help!
